### ISSUE TITLE
Creating a Job with unknown provider will "mess up" the UI

### ISSUE THREAD

**Issue by gbena** [hakbot/hakbot-origin-controller#17]
When a new Job is submitted with an unknown provider (whether it is on purpose or not, ie typo entering the class name), then the UI will not show any Jobs anymore. Instead it will show "Loading, please wait"

Sample bad Job request:
{
  "name": "My Job",
  "provider": {
    "class": "io.hakbot.providers.shell.ShellProviderTest",
    "payload": {
      "command": "ls"
    }
  },
  "publisher": {
    "class": "io.hakbot.publishers.filesystem.FileSystemPublisher",
    "payload": {
      "publishPath": "/tmp/"
    }
  }
}

**Comment by gbena** [comment]
![2017-02-17-115516_1089x215_scrot](https://cloud.githubusercontent.com/assets/16888782/23079014/3a057d30-f508-11e6-95de-504f6ceb9d9c.png)

**Comment by gbena** [comment]
Note that retrieving Jobs from the RestAPI works fine. It is only the UI. Once that bad Job is deleted, the UI works again.

**Comment by stevespringett** [comment]
As a workaround, you can delete the UUID of the job in question until an updated snapshot is available with this fix.
